apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wanderlust
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Amar-Karale/DevOps-Projects.git
    targetRevision: master
    path: kubernetes
  destination:
    name: wanderlust
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
